import { RiskRegisterType } from ".";

export const simple_data : RiskRegisterType[] = [
    {
        consequence: "Major",
        existing_control: ['Conduct Sub-contractor training before work on site for Supervisor and Worker', 'Conduct daily tool box meeting', 'Close supervision by Main Contrcactor Supervisor'],
        hazard: ['Gas release and Fire causing Personal injury and property damage', 'Accident transportation cause property damage', 'injury to workman'],
        index: 0,
        initial_risk: "Medium",
        keys: 1,
        likelihood: "Possible",
        opp_threat: "-",
        overall_control_effectiveness: "-",
        review_comments: "-",
        review_days_to_due_date: "-",
        review_risk: "-",
        review_risk_status: "-",
        risk_action_Party: "sdsdsd",
        risk_consequence: "Major",
        risk_due_date: "close",
        risk_likelihood: "Likely",
        risk_no: 1,
        risk_residual_Risk: "Medium",
        risk_treatment_plan: "-sdsds",
        work_activity: "Working closely existing facility",
    },
    {
        consequence: "Major",
        existing_control: ['Conduct Sub-contractor training before work on site for Supervisor and Worker', 'Conduct daily tool box meeting', 'Close supervision by Main Contrcactor Supervisor'],
        hazard: ['Gas release and Fire causing Personal injury and property damage', 'Accident transportation cause property damage', 'injury to workman'],
        index: 0,
        initial_risk: "Medium",
        keys: 2,
        likelihood: "Possible",
        opp_threat: "-",
        overall_control_effectiveness: "-",
        review_comments: "-",
        review_days_to_due_date: "-",
        review_risk: "-",
        review_risk_status: "-",
        risk_action_Party: "sdsdsd",
        risk_consequence: "Major",
        risk_due_date: "close",
        risk_likelihood: "Likely",
        risk_no: 2,
        risk_residual_Risk: "Medium",
        risk_treatment_plan: "-sdsds",
        work_activity: "Working closely existing facility",
    },
    {
        consequence: "Major",
        existing_control: ['Conduct Sub-contractor training before work on site for Supervisor and Worker', 'Conduct daily tool box meeting', 'Close supervision by Main Contrcactor Supervisor'],
        hazard: ['Gas release and Fire causing Personal injury and property damage', 'Accident transportation cause property damage', 'injury to workman'],
        index: 0,
        initial_risk: "Medium",
        keys: 3,
        likelihood: "Possible",
        opp_threat: "-",
        overall_control_effectiveness: "-",
        review_comments: "-",
        review_days_to_due_date: "-",
        review_risk: "-",
        review_risk_status: "-",
        risk_action_Party: "sdsdsd",
        risk_consequence: "Major",
        risk_due_date: "close",
        risk_likelihood: "Likely",
        risk_no: 3,
        risk_residual_Risk: "Medium",
        risk_treatment_plan: "-sdsds",
        work_activity: "Working closely existing facility",
    },
    {
        consequence: "Major",
        existing_control: ['Conduct Sub-contractor training before work on site for Supervisor and Worker', 'Conduct daily tool box meeting', 'Close supervision by Main Contrcactor Supervisor'],
        hazard: ['Gas release and Fire causing Personal injury and property damage', 'Accident transportation cause property damage', 'injury to workman'],
        index: 0,
        initial_risk: "Medium",
        keys: 4,
        likelihood: "Possible",
        opp_threat: "-",
        overall_control_effectiveness: "-",
        review_comments: "-",
        review_days_to_due_date: "-",
        review_risk: "-",
        review_risk_status: "-",
        risk_action_Party: "sdsdsd",
        risk_consequence: "Major",
        risk_due_date: "close",
        risk_likelihood: "Likely",
        risk_no: 4,
        risk_residual_Risk: "Medium",
        risk_treatment_plan: "-sdsds",
        work_activity: "Working closely existing facility",
    },
    {
        consequence: "Major",
        existing_control: ['Conduct Sub-contractor training before work on site for Supervisor and Worker', 'Conduct daily tool box meeting', 'Close supervision by Main Contrcactor Supervisor'],
        hazard: ['Gas release and Fire causing Personal injury and property damage', 'Accident transportation cause property damage', 'injury to workman'],
        index: 0,
        initial_risk: "Medium",
        keys: 5,
        likelihood: "Possible",
        opp_threat: "-",
        overall_control_effectiveness: "-",
        review_comments: "-",
        review_days_to_due_date: "-",
        review_risk: "-",
        review_risk_status: "-",
        risk_action_Party: "sdsdsd",
        risk_consequence: "Major",
        risk_due_date: "close",
        risk_likelihood: "Likely",
        risk_no: 5,
        risk_residual_Risk: "Medium",
        risk_treatment_plan: "-sdsds",
        work_activity: "Working closely existing facility",
    }
]