export const data = [
  {
    key: 1,
    id: 1,
    number: 1,
    firstlast: 'นายสมหวัง บังเกิด',
    position: 'Project Manager',
    role: 'Company Admin',
    isuse: 'ใช้งาน',
    project_responsible: 'TP5-Phase3',
  },
  {
    key: 2,
    id: 2,
    number: 2,
    firstlast: 'นางสาวรัตนา แดงสนิท',
    position: 'SSHE Officer',
    role: 'SSHE Officer',
    isuse: 'ใช้งาน',
    project_responsible: 'New Plant Tank Farm2',
  },
  {
    key: 3,
    id: 3,
    number: 3,
    firstlast: 'นายกำจร อภัยวงศ์',
    position: 'หัวหน้าทีมไฟฟ้า',
    role: 'Staff',
    isuse: 'ใช้งาน',
    project_responsible: 'New Plant Tank Farm3',
  },
  {
    key: 4,
    id: 4,
    number: 4,
    firstlast: 'นายสมเกียรติ วงศ์ไทย',
    position: 'หัวหน้าทีมก่อสร้าง',
    role: 'Staff',
    isuse: 'ใช้งาน',
    project_responsible: 'TP5-Phase3',
  },
  {
    key: 5,
    id: 5,
    number: 5,
    firstlast: 'นายก่อเกิด ณ ลำปาง',
    position: 'IT Manager',
    role: 'SSHE Officer',
    isuse: 'ใช้งาน',
    project_responsible: 'TP5-Phase3',
  },
  {
    key: 6,
    id: 6,
    number: 6,
    firstlast: 'นางปวีณา จำเจริญใจ',
    position: 'Project CO-Ordinary',
    role: 'Company Admin',
    isuse: 'ใช้งาน',
    project_responsible: '10KmPipeto EEC',
  },
  {
    key: 7,
    id: 7,
    number: 7,
    firstlast: 'Mr.Stephen Bornjovee',
    position: 'IT Staff',
    role: 'Staff',
    isuse: 'ใช้งาน',
    project_responsible: '10KmPipeto EEC',
  },
];
