import moment from "moment"

export const incident_dummy_data = [
    {
        key : 1,
        Incident_Discription: "ทดสอบ1",
        Property_Damage_1: "ทดสอบ1 Property_Damage_1",
        Property_Damage_2: "ทดสอบ1 Property_Damage_2",
        Property_Damage_3: "ทดสอบ1 Property_Damage_3",
        Property_Damage_4: "ทดสอบ1 Property_Damage_4",
        acts_conditions_report: "Yes",
        address: "22/1 Samphantamit R.",
        age: "22",
        company: "Soho",
        company_activity: "xx",
        company_name: "asdasdasd",
        dateofincident: moment(new Date()),
        dateofreport: moment(new Date()),
        department: "asdasdas",
        incident_id: "l-x00191",
        locationofincident: "Tank Farm",
        month: moment(new Date()),
        name_team_member: "dasdas",
        nameofinjured: "asdasd",
        nationality: "Thai",
        personal_passport: "1309902664712",
        position: "dasdasd",
        prepared: "asdas",
        project: "ปรับปรุง Tank Farm",
        similar_incident_near_miss: "Yes",
        description_continued_on_attached_sheet: "Yes",
        sub_contractor: "asdasdasda",
        sug_option: ['Stop this activity', 'Guard the hazard', 'Redesign work station', 'Write a new policy/rule', 'Personal Protective Equipment'],
        timeofincident: moment(new Date()),
        timeofreport: moment(new Date()),
        typeofincident: ['Fatality', 'Lost Workday', 'Medical Treatment', 'Fire Incident First Aid', 'Environmental Incident'],
        unsafe_acts_by_people: ['Operating without permission', 'Making a safety device inoperative', 'Taking an unsafe position or posture', 'Failure to use the available equipment / tools'],
        unsafe_acts_occur: "asdasdasdas",
        unsafe_conditions_exist: "asdasd",
        unsafe_workplace_conditions: ['Inadequate guard', 'Safety device is defective', 'Workstation layout is hazardous', 'Unsafe lighting', 'Lack of appropriate equipm ent/tools', 'Unsafe clothing'],
        year: moment(new Date())
    },
    {
        key : 2,
        Incident_Discription: "ทดสอบ1",
        Property_Damage_1: "ทดสอบ1 Property_Damage_1",
        Property_Damage_2: "ทดสอบ1 Property_Damage_2",
        Property_Damage_3: "ทดสอบ1 Property_Damage_3",
        Property_Damage_4: "ทดสอบ1 Property_Damage_4",
        acts_conditions_report: "Yes",
        address: "22/1 Samphantamit R.",
        age: "22",
        company: "Interset",
        company_activity: "xx",
        company_name: "asdasdasd",
        dateofincident: moment(new Date()),
        dateofreport: moment(new Date()),
        department: "asdasdas",
        incident_id: "l-x00192",
        locationofincident: "Tank Farm",
        month: moment(new Date()),
        name_team_member: "dasdas",
        nameofinjured: "asdasd",
        nationality: "Thai",
        personal_passport: "1309902664712",
        position: "dasdasd",
        prepared: "asdas",
        project: "ปรับปรุง Tank",
        similar_incident_near_miss: "Yes",
        description_continued_on_attached_sheet: "Yes",
        sub_contractor: "asdasdasda",
        sug_option: ['Stop this activity', 'Guard the hazard', 'Redesign work station', 'Write a new policy/rule', 'Personal Protective Equipment'],
        timeofincident: moment(new Date()),
        timeofreport: moment(new Date()),
        typeofincident: ['Fatality', 'Lost Workday', 'Medical Treatment', 'Fire Incident First Aid', 'Environmental Incident'],
        unsafe_acts_by_people: ['Operating without permission', 'Making a safety device inoperative', 'Taking an unsafe position or posture', 'Failure to use the available equipment / tools'],
        unsafe_acts_occur: "asdasdasdas",
        unsafe_conditions_exist: "asdasd",
        unsafe_workplace_conditions: ['Inadequate guard', 'Safety device is defective', 'Workstation layout is hazardous', 'Unsafe lighting', 'Lack of appropriate equipm ent/tools', 'Unsafe clothing'],
        year: moment(new Date())
    }
]